name: login
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase y Supabase
  supabase_flutter: ^2.8.4
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0

  # Utilidades
  provider: ^6.0.5
  intl: ^0.20.2
  crypto: ^3.0.0
  flutter_animate: ^4.1.1+1
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  http: 1.3.0
  

  # Mapas
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  mapbox_search: ^4.3.1
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Logop.png
    - assets/fondo.jpg
