// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0V4_Z9eyivUNN0BKP4c0AFR5RTEBnSt8',
    appId: '1:825929016776:web:d84f5d0bb212a866364cfd',
    messagingSenderId: '825929016776',
    projectId: 'careid-78bba',
    authDomain: 'careid-78bba.firebaseapp.com',
    storageBucket: 'careid-78bba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE2QKaXQRxtWM2uf46q6A60a05DWVMEWM',
    appId: '1:825929016776:android:da0b509c2621b511364cfd',
    messagingSenderId: '825929016776',
    projectId: 'careid-78bba',
    storageBucket: 'careid-78bba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5zQGimGrNTeTFoBplyfLZYMFMt1snDYM',
    appId: '1:825929016776:ios:38750d49a21ed9fd364cfd',
    messagingSenderId: '825929016776',
    projectId: 'careid-78bba',
    storageBucket: 'careid-78bba.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5zQGimGrNTeTFoBplyfLZYMFMt1snDYM',
    appId: '1:825929016776:ios:38750d49a21ed9fd364cfd',
    messagingSenderId: '825929016776',
    projectId: 'careid-78bba',
    storageBucket: 'careid-78bba.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0V4_Z9eyivUNN0BKP4c0AFR5RTEBnSt8',
    appId: '1:825929016776:web:5471b0076c5f91b5364cfd',
    messagingSenderId: '825929016776',
    projectId: 'careid-78bba',
    authDomain: 'careid-78bba.firebaseapp.com',
    storageBucket: 'careid-78bba.firebasestorage.app',
  );
}
